/**
 * superadobe.js
 * Geometry engine for superadobe structures.
 *
 * References:
 *  [1] López, González, Llauradó — "Equations that describe the geometry of
 *      Superadobe domed structures" (3er CIIE, UPM).
 *  [2] López Gómez, M.A. — "A study of the geometry and structural performance
 *      of Superadobe domes" (Doctoral thesis, UPM, 2021).
 *
 * Core model ([1], [2] ch.5): the dome is generated by REVOLVING an offset
 * circular arc about the vertical (y) axis.
 *
 *   Inner ring radius at height h  (eq. 1''):
 *       x(h) = Rb                                   0 <= h <= h1   (cyl. base)
 *       x(h) = sqrt((Rb+a)^2 - (h-h1)^2) - a        h1 <  h <= H
 *
 *   Total height (eq. 3'):  H = h1 + sqrt((Rb+a)^2 - (Rt+a)^2)
 *
 * Sack cross-section ([2] §5.3.1): an OVAL of width sw and height hs — bags
 * are rendered as elliptical-section rings swept along each layer curve.
 *
 * Empirical rules implemented ([2] §3.6.7–3.6.9):
 *  - Table 3-1: sack width/height as a function of internal base diameter.
 *  - Quadrant rule: max one opening per imaginary quadrant (≤4 total), wall
 *    arcs between openings ≥ 1.25 m.
 *  - Apses/intersections: sacks stop at the intersection points of two domes,
 *    each dome abiding by its own compass. Ideal apse: center on the outer
 *    edge of the main dome's base sack, outer base edge → main apex at 45°.
 *  - Door halls: a deep door mold guides a corridor between/out of domes.
 */

const SuperAdobe = (() => {

  const TWO_PI = Math.PI * 2;

  // ─── Dome profile: revolved offset circular arc ──────────────────────────
  function domeProfile(opts) {
    const Rb   = opts.baseRadius;
    const sw   = opts.sackWidthCm / 100;
    const hs   = opts.courseHeightCm / 100;
    const a    = Math.max(0, opts.archOffset || 0);
    const Rt   = Math.max(0.05, opts.skylightRadius != null ? opts.skylightRadius : 0.25);
    const h1   = Math.max(0, opts.baseWallHeight || 0);

    const Rarc = Rb + a;
    const Lflat = Math.max(0.01, sw - hs);  // flat bearing width of the stadium
    const courses = [];

    let y = hs / 2;

    while (y < h1 - 1e-6) {
      courses.push({ y, r: Rb + sw / 2, inner: Rb });
      y += hs;
    }

    // Rings exist ONLY on the hs grid (§3.6.6: each course is one bag height
    // above the last — there is no ring at an arbitrary height). The profile
    // ends at the last grid course that (a) still lies outside the requested
    // skylight radius and (b) actually RESTS on the course below: a course
    // whose inward step exceeds the flat bearing width Lflat would float in
    // the air (paper eq. 8' with F ≤ 0, Figs 9–11), so it is refused. The
    // ACHIEVED skylight radius is the last course's inner radius — tr is a
    // lower bound (the thesis calls it "tmin"), not a ring of its own.
    let truncated = false;
    while (true) {
      const dh = y - h1;
      const inside = Rarc * Rarc - dh * dh;
      if (inside <= 0) break;
      const xInner = Math.sqrt(inside) - a;
      if (xInner <= Rt) break;
      const prev = courses[courses.length - 1];
      if (prev && (prev.inner - xInner) > Lflat) { truncated = true; break; }
      courses.push({ y, r: xInner + sw / 2, inner: Math.max(0, xInner) });
      y += hs;
    }

    if (!courses.length) courses.push({ y: hs / 2, r: Rb + sw / 2, inner: Rb });
    courses.truncated = truncated;   // stopped short: next course would float

    return courses;
  }

  // ─── Geometric coherency F (paper eq. 8', generalised to every pair) ──────
  // For each pair of consecutive rings, F = (L − step) / L: the fraction of the
  // flat bag width L = sw − hs still resting on the ring below (step = inward
  // shift of the inner faces). Returns the worst pair — the paper's
  // "geometric coherency" of the dome — plus whether the profile stopped short
  // of the requested skylight radius because further courses would float.
  function coherency(profile, sackWidthCm, courseHeightCm) {
    const sw = sackWidthCm / 100, hs = courseHeightCm / 100;
    const L = Math.max(0.01, sw - hs);
    let minF = 1, atCourse = 0;
    for (let i = 1; i < profile.length; i++) {
      const step = profile[i - 1].inner - profile[i].inner;
      const F = Math.max(0, Math.min(1, (L - step) / L));
      if (F < minF) { minF = F; atCourse = i; }
    }
    const achievedRt = profile.length ? profile[profile.length - 1].inner : 0;
    return { minF, atCourse, L, achievedRt, truncated: !!profile.truncated };
  }

  function domeHeight(opts) {
    const Rb = opts.baseRadius;
    const a  = Math.max(0, opts.archOffset || 0);
    const Rt = Math.max(0.05, opts.skylightRadius != null ? opts.skylightRadius : 0.25);
    const h1 = Math.max(0, opts.baseWallHeight || 0);
    const Rarc = Rb + a;
    return h1 + Math.sqrt(Math.max(0, Rarc * Rarc - (Rt + a) * (Rt + a)));
  }

  // ─── Cylinder profile ────────────────────────────────────────────────────
  function cylinderProfile(opts) {
    const Rb = opts.baseRadius;
    const sw = opts.sackWidthCm / 100;
    const hs = opts.courseHeightCm / 100;
    const courses = [];
    let y = hs / 2;
    while (y <= opts.wallHeight + hs / 2) {
      courses.push({ y, r: Rb + sw / 2, inner: Rb });
      y += hs;
    }
    return courses;
  }

  // ─── Vault profile ───────────────────────────────────────────────────────
  function vaultProfile(opts) {
    const half = domeProfile(opts);
    return { half, length: opts.vaultLength };
  }

  // ─── Table 3-1: recommended sack size for an internal base diameter ──────
  function recommendedSack(diameterM) {
    if (diameterM <= 3)   return { sw: 30, hs: 8.5 };
    if (diameterM <= 3.5) return { sw: 35, hs: 9.5 };
    if (diameterM <= 4)   return { sw: 40, hs: 10 };
    if (diameterM <= 4.5) return { sw: 45, hs: 13 };
    return { sw: 50, hs: 14 };
  }

  // ─── Empirical opening rules (thesis §3.6.7 molds + §3.6.9 design rules) ──
  // These are the *limitations* the construction method imposes on openings:
  //  • Max 4 openings, one per imaginary quadrant; the curved wall arc left
  //    between any two adjacent openings must be ≥ 1.25 m (§3.6.9).
  //  • Ideal door 1.5 m wide × 1.8 m clear height; ideal window 1.0 × 1.5 m
  //    (§3.6.7). Wider/taller openings need a lintel or buttress.
  //  • Window sill 1.0–1.5 m; door from the floor (mold set 0.2–0.6 m up).
  //  • Internal base diameter > 1.5 m → buttresses/apses recommended (§3.6.9).
  //  • An opening's arc must fit the dome (compass sweep ≤ ~124° per §3.6.7).
  const OPENING_RULES = {
    maxOpenings: 4,
    minWallArc: 1.25,                 // m, between adjacent openings (§3.6.9)
    idealDoor:   { w: 1.5, h: 1.8 },  // m (§3.6.7)
    idealWindow: { w: 1.0, h: 1.5 },  // m (§3.6.7)
    windowSill:  [1.0, 1.5],          // m range (§3.6.7)
    buttressDiameter: 1.5,            // m, above which buttresses are advised (§3.6.9)
    maxSweep: 124 * Math.PI / 180,    // rad, widest arc one opening may span (§3.6.7)
  };

  // ─── Openings: quadrant placement (§3.6.7 / §3.6.9) ──────────────────────
  // One opening per imaginary quadrant: door(s) first, then windows, each in
  // its own quadrant slot at facing + k·90°. Dimensions are clamped to the
  // §3.6.7 ideals (door ≤ 1.5×1.8, window 1.0×1.5) and to the dome height.
  function computeOpenings(p, totalHeight) {
    const openings = [];
    const facing = p.doorFacingRad != null ? p.doorFacingRad : 0;
    const total = Math.min(OPENING_RULES.maxOpenings, (p.doors || 0) + (p.windows || 0));

    // §3.6.7: molds sit ON TOP of a finished ring, so every sill and
    // springline must land on a course boundary — a course is either laid past
    // a mold or stopped at it, never cut to a fraction of its height.
    const ch = Math.max(0.04, (p.courseHeightCm || 12) / 100);
    const snapUp = v => Math.ceil(v / ch - 1e-9) * ch;
    const snapDn = v => Math.floor(v / ch + 1e-9) * ch;

    // Door: the mold is set once the wall reaches 0.2–0.6 m (§3.6.7, Fig 3-18),
    // so the base courses run CONTINUOUSLY under the doorway — a raised
    // threshold of whole courses, the strongest tie in the structure.
    const doorSill = snapUp(0.2);
    // §3.6.7 ideal geometry, clamped so a short dome still closes above the head.
    const clearH = Math.max(2 * ch,
      Math.min(OPENING_RULES.idealDoor.h, totalHeight * 0.82 - doorSill)); // ideal 1.8 m above the mold base
    const doorSpring = snapUp(doorSill + clearH);   // head bag rests on a full course
    const winH = OPENING_RULES.idealWindow.h;                                // 1.5 m
    const winSill = snapUp(Math.min(OPENING_RULES.windowSill[0], totalHeight * 0.32)); // ideal ~1.0 m sill
    const winTop = Math.max(winSill + ch, snapDn(Math.min(winSill + winH, totalHeight * 0.82)));

    // Door head shape determines how the arch rises above the clear height.
    const headShape = p.doorHeadShape || 'flat';
    const doorW = Math.min(OPENING_RULES.idealDoor.w, (p.doorWidthCm || 90) / 100); // cap at ideal 1.5 m
    const archH = headShape === 'semicircle' ? doorW / 2
                : headShape === 'arc'        ? (p.doorArcHeight || 0.4)
                : 0;  // flat: no arch above clear height

    let slot = 0;
    for (let i = 0; i < Math.min(p.doors || 0, total); i++, slot++) {
      openings.push({
        kind: 'door',
        angle: facing + slot * Math.PI / 2,
        width: doorW,
        bottom: doorSill,          // threshold courses run under the door
        springline: doorSpring,    // where the head curve starts
        top: doorSpring + archH,   // topmost point of the opening profile
        headShape,
        arcHeight: archH,
        bagWidthCm: p.bagWidthCm,  // for the alternating door-jamb seam
        corridor: !!p.corridor,    // jambs pass through the wall → cut the dome
      });
    }
    // Circular ("oculus") window geometry, when chosen. Its mold also rests on
    // a finished ring, so the circle's BOTTOM lands on a course boundary.
    const winShape = p.windowShape || 'rect';
    const winRad = Math.max(0.2, (p.windowDiameterCm || 80) / 200);   // diameter→radius
    const rawCy = Math.max(winRad + 0.5, Math.min(totalHeight * 0.5, winSill + winRad));
    const winCy = Math.max(ch, Math.round((rawCy - winRad) / ch) * ch) + winRad; // centre height

    for (let i = 0; slot < total; i++, slot++) {
      if (winShape === 'circle') {
        openings.push({
          kind: 'window',
          shape: 'circle',
          angle: facing + slot * Math.PI / 2,
          width: winRad * 2,
          radius: winRad,
          cy: winCy,                 // centre height
          bottom: winCy - winRad,
          springline: winCy + winRad,
          top: winCy + winRad,
          headShape: 'flat',
          arcHeight: 0,
        });
      } else {
        openings.push({
          kind: 'window',
          shape: 'rect',
          angle: facing + slot * Math.PI / 2,
          width: OPENING_RULES.idealWindow.w,
          bottom: winSill,
          springline: winTop,
          top: winTop,
          headShape: 'flat',
          arcHeight: 0,
        });
      }
    }
    return openings;
  }

  // ─── Opening validation (thesis §3.6.7 + §3.6.9) ─────────────────────────
  // Returns array of warning strings (empty = compliant). `opts` may carry
  // { domeHeight, hasButtress } for the height-feasibility and buttress rules.
  function validateOpenings(p, baseRadius, opts) {
    opts = opts || {};
    const W = [];
    const R = baseRadius;
    const doors = p.doors || 0, windows = p.windows || 0;
    const count = doors + windows;

    // §3.6.9 — quadrant rule: max 4 openings, one per imaginary quadrant.
    if (count > OPENING_RULES.maxOpenings) {
      W.push(`Quadrant rule (§3.6.9): max 4 openings — one per imaginary quadrant. ${count} requested; only 4 are built.`);
    }

    // §3.6.7 — ideal door 1.5 × 1.8 m.
    const doorW = (p.doorWidthCm || 90) / 100;
    if (doors > 0 && doorW > OPENING_RULES.idealDoor.w + 1e-6) {
      W.push(`Door ${doorW.toFixed(2)} m wide exceeds the ideal 1.5 m (§3.6.7) — it is capped at 1.5 m. Wider needs a lintel.`);
    }

    const openings = computeOpenings(p, opts.domeHeight || 100);

    // §3.6.7 — a single opening must fit the dome (compass sweep ≤ ~124°).
    for (const o of openings) {
      const sweep = o.width / Math.max(0.2, R);   // arc angle the opening spans
      if (sweep > OPENING_RULES.maxSweep) {
        const lbl = o.kind === 'door' ? 'Door' : 'Window';
        W.push(`${lbl} (${o.width.toFixed(2)} m) is too wide for a Ø ${(2 * R).toFixed(1)} m dome — its arc spans ${(sweep * 180 / Math.PI).toFixed(0)}° (max ~124°). Enlarge the dome.`);
      }
    }

    // §3.6.9 — wall arc between adjacent openings ≥ 1.25 m. The rings shrink
    // with height (x(h)), so the arc is SHORTEST up where the openings sit,
    // not at the base — evaluate over the heights where both are open, on the
    // wall centreline at that height. Falls back to the base radius when no
    // profile is passed in `opts.profile`.
    const prof = opts.profile;
    const swM = (p.bagWidthCm || 50) / 100;
    const radiusAt = h => {
      if (!prof || !prof.length) return R;
      const rc = outerRadiusAt(prof, swM / 2, h);
      return rc == null ? R : rc;
    };
    // Opening half-width (m) at height h (0 outside the opening).
    const halfW = (o, h) => {
      if (h <= (o.bottom || 0) + 1e-9 || h >= o.top - 1e-9) return 0;
      if (o.shape === 'circle') {
        const dy = Math.abs(h - o.cy);
        const sq = o.radius * o.radius - dy * dy;
        return sq > 0 ? Math.sqrt(sq) : 0;
      }
      const sl = o.springline != null ? o.springline : o.top;
      if (h <= sl) return o.width / 2;
      const dy = h - sl;
      if (o.headShape === 'semicircle') {
        const sq = (o.width / 2) ** 2 - dy * dy;
        return sq > 0 ? Math.sqrt(sq) : 0;
      }
      if (o.headShape === 'arc') {
        const arcH = o.arcHeight || 0.4, hw = o.width / 2;
        const Rc = (hw * hw + arcH * arcH) / (2 * arcH);
        const sq = Rc * Rc - (dy - (arcH - Rc)) * (dy - (arcH - Rc));
        return sq > 0 ? Math.sqrt(sq) : 0;
      }
      return 0;
    };
    if (openings.length >= 2) {
      const sorted = openings.slice().sort((a, b) => a.angle - b.angle);
      let worst = Infinity, gapAng = Math.PI / 2;
      for (let i = 0; i < sorted.length; i++) {
        const cur = sorted[i], nxt = sorted[(i + 1) % sorted.length];
        const dAng = (i === sorted.length - 1) ? (nxt.angle + TWO_PI - cur.angle) : (nxt.angle - cur.angle);
        const hLo = Math.max(cur.bottom || 0, nxt.bottom || 0);
        const hHi = Math.min(cur.top, nxt.top);
        let wallArc;
        if (hHi > hLo + 1e-6) {
          wallArc = Infinity;
          for (let k = 0; k <= 6; k++) {
            const h = hLo + 1e-6 + (k / 6) * (hHi - hLo - 2e-6);
            const arc = radiusAt(h) * dAng - halfW(cur, h) - halfW(nxt, h);
            if (arc < wallArc) wallArc = arc;
          }
        } else {
          wallArc = R * dAng - cur.width / 2 - nxt.width / 2;  // never open together
        }
        if (wallArc < worst) { worst = wallArc; gapAng = dAng; }
      }
      if (worst < OPENING_RULES.minWallArc) {
        const needR = (OPENING_RULES.minWallArc + doorW) / Math.max(0.1, gapAng); // rough min base radius
        W.push(`Wall between openings is ${worst.toFixed(2)} m at opening height — must be ≥ 1.25 m (§3.6.9). Narrow the openings, or enlarge the dome to about Ø ${(2 * needR).toFixed(1)} m.`);
      }
    } else if (openings.length === 1) {
      const o = openings[0];
      const hMid = ((o.bottom || 0) + o.top) / 2;
      const wallArc = TWO_PI * radiusAt(hMid) - o.width;
      if (wallArc < OPENING_RULES.minWallArc) {
        W.push(`Opening leaves only ${wallArc.toFixed(2)} m of wall — must be ≥ 1.25 m (§3.6.9).`);
      }
    }

    // §3.6.7 — dome must be tall enough for a full-height opening.
    if (opts.domeHeight && doors > 0 && opts.domeHeight * 0.82 < OPENING_RULES.idealDoor.h - 0.05) {
      W.push(`Dome is short — door clear height limited to ${(opts.domeHeight * 0.82).toFixed(2)} m (ideal 1.8 m, §3.6.7).`);
    }

    return W;
  }

  // Largest door width (m) that still leaves ≥1.25 m walls, given the current
  // opening layout — used by the UI hint. Returns the ideal 1.5 m cap at most.
  function maxDoorWidth(p, baseRadius) {
    const R = baseRadius, n = Math.min(OPENING_RULES.maxOpenings, (p.doors || 0) + (p.windows || 0));
    if (n <= 0) return OPENING_RULES.idealDoor.w;
    // openings sit 90° apart; neighbour is a window (1.0 m) or door.
    const gap = Math.PI / 2;                    // smallest spacing used
    const neighbourHalf = ((p.windows || 0) > 0 ? OPENING_RULES.idealWindow.w : OPENING_RULES.idealDoor.w) / 2;
    // R·gap − doorW/2 − neighbourHalf ≥ 1.25  ⇒  doorW ≤ 2(R·gap − 1.25 − neighbourHalf)
    const fit = 2 * (R * gap - OPENING_RULES.minWallArc - neighbourHalf);
    return Math.max(0, Math.min(OPENING_RULES.idealDoor.w, fit));
  }

  // The door/window reveal in the dome is a CLEAN vertical edge (a symmetric
  // gap) — the dome courses must not stagger into the doorway. The alternating
  // intersection-rule interlock lives entirely in the corridor jambs (they tuck
  // into the solid wall beside the opening, see buildCorridorGeometries), not in
  // the dome's opening edges. `courseIndex` is accepted for call-site symmetry
  // but the door reveal stays clean regardless.
  //
  // MOLD / BUFFER (door head): the head curve (semicircle/arc) is the shape of a
  // MOLD set in the opening. A flat course BRIDGES over the opening as soon as
  // the mold has closed below its UNDERSIDE — so the cut is evaluated at the
  // course's bottom edge `y − ch/2` (pass `courseHeightM`), removing only as much
  // as the mold actually intrudes. The result: the 2–3 courses straddling the
  // crown get a small notch (the buffer), and every course whose underside
  // clears the crown stays a flat full ring. Omit `courseHeightM` (shell, dy=0.1
  // sampling) to evaluate the exact mold curve at the sample height.
  function openingGaps(y, r, openings, courseIndex, courseHeightM) {
    if (!openings || !openings.length) return [];
    const chM = courseHeightM || 0;
    const yBot = y - chM / 2, yTop = y + chM / 2;   // course underside / top
    const gaps = [];
    for (const o of openings) {
      // Boundary-touching courses stay whole: sills/springlines sit exactly on
      // course boundaries (molds rest on finished rings), so a course whose
      // top edge IS the sill — or whose underside IS the head — is not cut.
      if (yTop <= o.bottom + 1e-6 || yBot >= o.top - 1e-6) continue;

      // Circular ("oculus") window: the gap is the CHORD of the circle at this
      // height. Carve at whichever course edge is nearer the centre so the round
      // hole is cut as wide as the circle reaches into the course.
      if (o.shape === 'circle') {
        const dyc = (chM > 0)
          ? Math.max(0, Math.abs(y - o.cy) - chM / 2)   // nearest edge of the band to the centre
          : Math.abs(y - o.cy);
        const sq = o.radius * o.radius - dyc * dyc;
        if (sq <= 0) continue;
        const hw = Math.sqrt(sq) / Math.max(0.2, r);
        gaps.push([o.angle - hw, o.angle + hw]);
        continue;
      }

      // Half-width (m) of the opening — for the head, carved to the mold at the
      // course UNDERSIDE so only the buffer courses near the crown are cut.
      let halfWidthM = o.width / 2;
      const sl = o.springline != null ? o.springline : o.top;
      const yEval = chM > 0 ? yBot : y;
      if (yEval > sl) {
        const dy = yEval - sl;
        const hs = o.headShape || 'flat';
        if (hs === 'semicircle') {
          const archR = o.width / 2;
          const sq = archR * archR - dy * dy;
          if (sq <= 0) continue;
          halfWidthM = Math.sqrt(sq);
        } else if (hs === 'arc') {
          const arcH = o.arcHeight || 0.4;
          const hw = o.width / 2;
          const R = (hw * hw + arcH * arcH) / (2 * arcH);
          const sq = R * R - (dy - (arcH - R)) * (dy - (arcH - R));
          if (sq <= 0) continue;
          halfWidthM = Math.sqrt(sq);
        } else {
          continue; // flat: no opening above springline
        }
      }
      if (halfWidthM <= 0) continue;
      const rr = Math.max(0.2, r);

      // Door jamb interlock. The corridor's COVER jambs run through the wall to
      // the inner dome face (see buildCorridorGeometries), so on those courses
      // the dome ring would collide with the jamb. CUT the dome back by one bag
      // on that side to make the notch the jamb sits in — the BUTT side stays a
      // clean reveal. Sides swap every course (diagonal weave). Only below the
      // head (jamb region) and only when a corridor is present; head courses and
      // the smooth shell (no courseIndex) keep the clean mold reveal.
      const swO = (o.bagWidthCm || 0) / 100;
      const inJamb = chM > 0 ? (yTop <= sl + 1e-6) : (y <= sl + 1e-6);
      if (courseIndex != null && o.kind === 'door' && o.corridor && swO > 0 && inJamb) {
        const plusCut = (courseIndex % 2) === 1;     // +side jamb covers this course
        const hwPlusM  = halfWidthM + (plusCut ? swO : 0);
        const hwMinusM = halfWidthM + (plusCut ? 0 : swO);
        gaps.push([o.angle - hwMinusM / rr, o.angle + hwPlusM / rr]);
      } else {
        gaps.push([o.angle - halfWidthM / rr, o.angle + halfWidthM / rr]);
      }
    }
    return gaps;
  }

  // ─── Dome intersection gaps (§3.6.8 apses) ───────────────────────────────
  // Sacks STOP at the points of intersection of two domes. For a course of
  // structure `me` at height y and mid radius rMid, returns the angular gap(s)
  // (in me's LOCAL frame) where the ring would run inside a neighbor's wall.
  // Returns null if the ring is entirely swallowed (course not built).
  //
  // `courseIndex` (optional) turns on the alternating sewn seam: each course,
  // ONE dome reaches the intersection line while its neighbour begins a
  // bag-width past it, and the roles swap every course (§3.6.8 "alternating a
  // sack on top from the main dome / from the apse"). Omit it (shell + material
  // estimate) for a plain clean union where both domes stop at the line.
  function intersectionGaps(me, others, y, rMid, courseIndex) {
    const gaps = [];
    const meRot = (me.rotDeg || 0) * Math.PI / 180;
    const swMe = me.bagWidthCm / 100;

    for (const o of others) {
      if (o.id === me.id) continue;
      if (o.type !== 'dome' && o.type !== 'cylinder') continue;
      const prof = o.profile;
      if (!prof || !prof.length) continue;

      // Radius of the neighbour to trim against. For the shell/union use its
      // OUTER wall (watertight merge). For laying courses use its CENTERLINE
      // (mid radius): the covering course then reaches the neighbour's own bag
      // centreline, so the two domes' bags overlap and INTERLOCK at the seam
      // instead of leaving a half-bag gap between the walls.
      const swO = o.bagWidthCm / 100;
      const outerR = outerRadiusAt(prof, courseIndex != null ? swO / 2 : swO, y);
      if (outerR == null) continue;                  // neighbor shorter than y

      const dx = (o.x || 0) - (me.x || 0);
      const dz = (o.z || 0) - (me.z || 0);
      const d = Math.hypot(dx, dz);
      if (d < 1e-6 || d >= rMid + outerR) continue;  // concentric or no overlap

      const cosArg = (d * d + rMid * rMid - outerR * outerR) / (2 * d * rMid);
      if (cosArg >= 1) continue;                     // no intersection
      if (cosArg <= -1) return null;                 // ring fully inside neighbor

      const phi = Math.acos(cosArg);
      // World azimuth me→neighbor, converted to me's local frame
      // (world az = local az − rotY  =>  local az = world az + rotY)
      const worldAng = Math.atan2(dz, dx);
      const localAng = worldAng + meRot;

      if (courseIndex == null) {
        // Clean union (shell / material estimate): both stop at the line.
        gaps.push([localAng - phi, localAng + phi]);
        continue;
      }

      // Alternating sewn seam (§3.6.8). The seam has TWO junctions (the ends of
      // the shared chord). At each, one dome's course COVERS — reaching the
      // intersection line — and the other BUTTS, its curve ending HALF a
      // bag-width short. Ownership swaps between the two junctions (diagonal
      // interlock) and flips every course. Both domes share a canonical axis
      // (lower-id → higher-id centre) so they always come out complementary.
      const h = (swMe / 2) / Math.max(0.2, rMid);          // half-bag angle
      const lo = me.id < o.id ? me : o, hi = me.id < o.id ? o : me;
      const cax = (hi.x || 0) - (lo.x || 0), caz = (hi.z || 0) - (lo.z || 0);
      const meIsLo = me.id < o.id;
      const meCovers = (px, pz) => {
        const side = (cax * (pz - (lo.z || 0)) - caz * (px - (lo.x || 0))) >= 0 ? 0 : 1;
        const loCovers = ((courseIndex + side) % 2) === 0;
        return meIsLo ? loCovers : !loCovers;
      };
      const ppx = (me.x || 0) + rMid * Math.cos(worldAng + phi);
      const ppz = (me.z || 0) + rMid * Math.sin(worldAng + phi);   // +phi junction
      const pmx = (me.x || 0) + rMid * Math.cos(worldAng - phi);
      const pmz = (me.z || 0) + rMid * Math.sin(worldAng - phi);   // −phi junction
      // Symmetric half-bag offset: the covering course extends HALF a bag PAST
      // the intersection line (offset −h) and the butting course ends HALF a bag
      // SHORT of it (offset +h), leaving the clean alternating gap of the sketch.
      const offP = meCovers(ppx, ppz) ? -h : h;
      const offM = meCovers(pmx, pmz) ? -h : h;
      gaps.push([localAng - (phi + offM), localAng + (phi + offP)]);
    }
    return gaps;
  }

  // Outer wall radius (inner + sack width) of a profile at height y, or null.
  function outerRadiusAt(profile, sw, y) {
    const last = profile[profile.length - 1];
    if (y > last.y + 1e-6) return null;
    if (y <= profile[0].y) return profile[0].inner + sw;
    for (let i = 1; i < profile.length; i++) {
      if (profile[i].y >= y) {
        const a = profile[i - 1], b = profile[i];
        const t = (y - a.y) / Math.max(1e-6, b.y - a.y);
        return a.inner + (b.inner - a.inner) * t + sw;
      }
    }
    return last.inner + sw;
  }

  // ─── Base buttress courses (§3.6.8–3.6.9) ────────────────────────────────
  // Buttresses are an extra wall of sacks around the dome's base, sewn to the
  // base rings with barbed-wire "s"s, and must always be built to 50 cm above
  // the springline (the top of the cylindrical base wall h1; 3–5 rings above
  // it). Each course hugs the dome's outer face at its own height. Returns
  // centreline courses [{y, r}] in the structure's local frame.
  function buttressCourses(profile, sackWidthCm, courseHeightCm, baseWallHeight) {
    if (!profile || !profile.length) return [];
    const sw = sackWidthCm / 100;
    const hs = courseHeightCm / 100;
    const topY = (baseWallHeight || 0) + 0.5;      // springline + 50 cm
    const courses = [];
    for (let y = hs / 2; y <= topY + 1e-6; y += hs) {
      const face = outerRadiusAt(profile, sw, y);  // dome outer face here
      if (face == null) break;
      courses.push({ y, r: face + sw / 2, inner: face });
    }
    return courses;
  }

  // ─── Ideal apse parameters (§3.6.8 / §3.6.9) ─────────────────────────────
  // Center on the outer edge of the main dome's base sack; line from apse's
  // outer base edge to the main dome's apex at 45° with the ground.
  function idealApse(main, mainHeight) {
    const swMain = main.bagWidthCm / 100;
    const dist = main.diameter / 2 + swMain;            // apse center distance
    const swApse = swMain;                              // same sacks
    let baseR = mainHeight - dist - swApse;             // 45° rule: H = dist + RbA + swA
    baseR = Math.max(0.6, Math.min(baseR, main.diameter / 2 * 0.9));
    return { dist, baseRadius: baseR };
  }

  // ─── Plane-slice of the complex at height y (the "spin + boolean" model) ──
  // Each surface-of-revolution dome, sliced by a horizontal plane, is a circle.
  // The kept arcs are those OUTSIDE every other dome (union of the solids) and
  // outside any opening. Returns the kept angular spans (LOCAL frame) for `s`
  // at world height y and the given radius, or [] if fully inside a neighbour.
  function sliceSpans(s, others, y, radius, openings) {
    const og = openingGaps(y, radius, openings);
    const ig = intersectionGaps(s, others, y, radius);
    if (ig === null) return [];               // wall entirely inside a neighbour
    return solidSpans(og.concat(ig));
  }

  // ─── LAYOUT shell: loft the slice-curves into one unified surface ─────────
  // Stage 1 of the engine. The dome profile is revolved about the y axis
  // (Blender "spin"); the surface is trimmed where it enters a neighbouring
  // dome or a doorway, and all domes share the union boundary so the result
  // reads as a single welded monolith. Built in the structure's LOCAL frame
  // (the scene group applies its position/rotation).
  function buildShellGeometry(s, others) {
    const prof = s.profile;
    if (!prof || prof.length < 2) return null;
    const sw = s.bagWidthCm / 100;
    const H = prof[prof.length - 1].y;
    const openings = computeOpenings(s, H);

    const angN = 128;                         // angular resolution
    const dy = 0.1;                           // vertical sampling (m)
    const hN = Math.max(4, Math.ceil(H / dy));

    // Per height level: surface radius + kept angular spans. The structure
    // surface runs through the bag CENTRELINE (inner + sw/2), so the centre of
    // each bag course curve lies on the surface (not its outer face).
    const levels = [];
    for (let i = 0; i <= hN; i++) {
      const y = (i / hN) * H;
      const R = outerRadiusAt(prof, sw / 2, y);
      if (R == null) { levels.push(null); continue; }
      levels.push({ y, R, spans: sliceSpans(s, others, y, R, openings) });
    }

    const inSpans = (spans, a) => {
      for (const [s0, s1] of spans) if (a >= s0 - 1e-9 && a <= s1 + 1e-9) return true;
      return false;
    };

    // Indexed vertex grid (height × angle); -1 where trimmed away
    const positions = [];
    const idx = [];
    let v = 0;
    for (let i = 0; i <= hN; i++) {
      idx[i] = [];
      const lv = levels[i];
      for (let j = 0; j <= angN; j++) {
        const a = (j / angN) * TWO_PI;
        if (lv && inSpans(lv.spans, a % TWO_PI)) {
          positions.push(Math.cos(a) * lv.R, lv.y, Math.sin(a) * lv.R);
          idx[i][j] = v++;
        } else idx[i][j] = -1;
      }
    }

    const indices = [];
    for (let i = 0; i < hN; i++) {
      for (let j = 0; j < angN; j++) {
        const a = idx[i][j], b = idx[i][j + 1];
        const c = idx[i + 1][j], d = idx[i + 1][j + 1];
        if (a >= 0 && b >= 0 && c >= 0 && d >= 0) indices.push(a, c, b, b, c, d);
      }
    }

    // Closed top: cap the apex with a smooth rounded dome over the opening.
    if (s.closedTop && levels[hN]) {
      const topR = levels[hN].R, capRise = topR, capN = 6;
      const ring = [];
      for (let c = 0; c < capN; c++) {
        const t = (c / capN) * (Math.PI / 2);
        const cr = topR * Math.cos(t), cy = H + capRise * Math.sin(t);
        ring[c] = [];
        for (let j = 0; j <= angN; j++) {
          const a = (j / angN) * TWO_PI;
          positions.push(Math.cos(a) * cr, cy, Math.sin(a) * cr);
          ring[c][j] = v++;
        }
      }
      positions.push(0, H + capRise, 0);
      const apex = v++;
      for (let c = 0; c < capN - 1; c++)
        for (let j = 0; j < angN; j++)
          indices.push(ring[c][j], ring[c + 1][j], ring[c][j + 1],
                       ring[c][j + 1], ring[c + 1][j], ring[c + 1][j + 1]);
      for (let j = 0; j < angN; j++)
        indices.push(ring[capN - 1][j], apex, ring[capN - 1][j + 1]);
    }

    if (!indices.length) return null;

    const geom = new THREE.BufferGeometry();
    geom.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
    geom.setIndex(indices);
    geom.computeVertexNormals();
    return geom;
  }

  // ─── Build one earthbag course ring (OVAL cross-section, §5.3.1) ─────────
  // Bags are sw wide × hs tall: an elliptical profile swept along the layer
  // curve. Returns an array of geometries (one per solid arc segment).
  // Bag cross-section = a STADIUM (capsule): a rectangle of width sw and
  // height hs with the two ends rounded by semicircles of radius hs/2 — flat
  // top/bottom (where courses stack & tamp), rounded inner/outer faces.
  // Returns [u, v] points around the section: u = radial (width), v = vertical.
  function stadiumSection(sw, hs, capSegs) {
    const R = hs / 2;
    const L = Math.max(0, sw / 2 - R);      // half-length of the straight part
    const pts = [];
    for (let i = 0; i <= capSegs; i++) {    // outer (right) cap, bottom→top
      const a = -Math.PI / 2 + (i / capSegs) * Math.PI;
      pts.push([L + R * Math.cos(a), R * Math.sin(a)]);
    }
    for (let i = 0; i <= capSegs; i++) {    // inner (left) cap, top→bottom
      const a = Math.PI / 2 + (i / capSegs) * Math.PI;
      pts.push([-L + R * Math.cos(a), R * Math.sin(a)]);
    }
    return pts;                             // straight top/bottom are the wrap edges
  }

  // Sweep a 2-D `section` ([u,v]) centred on a horizontal curve. `pts` are
  // {x,z} centreline samples at constant height y; the curve passes through the
  // section centre, which sits in the plane of the local horizontal normal (u)
  // and the vertical axis (v). `capEnds` closes broken ring ends.
  function sweepSection(pts, y, section, capEnds) {
    const n = pts.length;
    if (n < 2) return null;
    const M = section.length;

    const rings = [];
    for (let i = 0; i < n; i++) {
      const prev = pts[Math.max(0, i - 1)];
      const next = pts[Math.min(n - 1, i + 1)];
      let tx = next.x - prev.x, tz = next.z - prev.z;
      const tl = Math.hypot(tx, tz) || 1; tx /= tl; tz /= tl;
      const nx = tz, nz = -tx;             // horizontal normal ⟂ tangent
      const ring = [];
      for (let k = 0; k < M; k++) {
        const u = section[k][0], v = section[k][1];
        ring.push([pts[i].x + nx * u, y + v, pts[i].z + nz * u]);
      }
      rings.push(ring);
    }

    const pos = [];
    for (let i = 0; i < n - 1; i++) {
      for (let k = 0; k < M; k++) {
        const k2 = (k + 1) % M;
        const a = rings[i][k], b = rings[i][k2], c = rings[i + 1][k], d = rings[i + 1][k2];
        pos.push(a[0], a[1], a[2], c[0], c[1], c[2], b[0], b[1], b[2]);
        pos.push(b[0], b[1], b[2], c[0], c[1], c[2], d[0], d[1], d[2]);
      }
    }
    if (capEnds) {
      [[0, false], [n - 1, true]].forEach(([i, flip]) => {
        const ring = rings[i], cx = pts[i].x, cz = pts[i].z;
        for (let k = 0; k < M; k++) {
          const a = ring[k], b = ring[(k + 1) % M];
          if (flip) pos.push(cx, y, cz, a[0], a[1], a[2], b[0], b[1], b[2]);
          else      pos.push(cx, y, cz, b[0], b[1], b[2], a[0], a[1], a[2]);
        }
      });
    }

    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    g.computeVertexNormals();
    return g;
  }

  function buildCourseGeometries(y, r, bagWidthCm, courseHeightCm, gaps, courseIndex) {
    const bw = bagWidthCm / 100;
    const ch = courseHeightCm / 100;
    const segsFull = Math.max(40, Math.round(r * 40));
    const section = stadiumSection(bw, ch, 5);        // capsule bag section

    let spans = solidSpans(gaps);

    // §3.6.6 staggered joints: a full (uninterrupted) ring — the perfect circles
    // above the openings — is one continuous CLOSED bag whose start/end joint
    // rotates 20° each course, so it spirals up the dome and no joint sits over
    // the one below. The ring stays closed (seamless full loop, no gap).
    const isFullRing = spans.length === 1 && (spans[0][1] - spans[0][0]) >= TWO_PI - 1e-6;
    if (isFullRing) {
      const start = (courseIndex || 0) * 20 * Math.PI / 180;
      spans = [[start, start + TWO_PI]];              // closed loop, joint at `start`
    }

    const geoms = [];
    for (const [a0, a1] of spans) {
      const sweep = a1 - a0;
      if (sweep <= 0.001) continue;
      const full = sweep >= TWO_PI - 1e-6;
      const nAlong = Math.max(3, Math.round(segsFull * sweep / TWO_PI));
      // Sample the course curve (this dome's slice arc) at mid radius r.
      const curve = [];
      for (let i = 0; i <= nAlong; i++) {
        const a = a0 + (i / nAlong) * sweep;
        curve.push({ x: Math.cos(a) * r, z: Math.sin(a) * r });
      }
      const g = sweepSection(curve, y, section, !full);   // cap the joint ends
      if (g) geoms.push(g);
    }
    return geoms;
  }

  // Complementary "solid" spans over [0,2π] for a set of angular gaps.
  function solidSpans(gaps) {
    if (!gaps || !gaps.length) return [[0, TWO_PI]];
    const norm = [];
    for (let [s, e] of gaps) {
      s = ((s % TWO_PI) + TWO_PI) % TWO_PI;
      e = ((e % TWO_PI) + TWO_PI) % TWO_PI;
      if (s <= e) norm.push([s, e]);
      else { norm.push([s, TWO_PI]); norm.push([0, e]); }
    }
    norm.sort((a, b) => a[0] - b[0]);
    const merged = [];
    for (const g of norm) {
      if (merged.length && g[0] <= merged[merged.length - 1][1] + 1e-6) {
        merged[merged.length - 1][1] = Math.max(merged[merged.length - 1][1], g[1]);
      } else merged.push([g[0], g[1]]);
    }
    const solid = [];
    let cursor = 0;
    for (const [s, e] of merged) {
      if (s > cursor + 1e-6) solid.push([cursor, s]);
      cursor = Math.max(cursor, e);
    }
    if (cursor < TWO_PI - 1e-6) solid.push([cursor, TWO_PI]);
    return solid;
  }

  // Fraction of the full circle that is actually built (for material calcs).
  function solidFraction(gaps) {
    if (gaps === null) return 0;
    const spans = solidSpans(gaps);
    let total = 0;
    for (const [a, b] of spans) total += (b - a);
    return total / TWO_PI;
  }

  // ─── Barbed wire strand ───────────────────────────────────────────────────
  // Builds ONE BufferGeometry (for THREE.LineSegments) that follows a path of
  // 3-D points as a single strand, with periodic X-shaped barbs that straddle
  // the wire in the tangent/vertical plane so they read as barbs from outside
  // the wall. `barbEvery` (spacing) and `barbLen` (barb half-size) are metres.
  function barbedStrand(points, barbEvery, barbLen) {
    const P = points.map(p => (p.isVector3 ? p : new THREE.Vector3(p.x, p.y, p.z)));
    const n = P.length;
    if (n < 2) return null;
    const pos = [];

    // Main strand: one line segment per span between consecutive samples.
    for (let i = 0; i < n - 1; i++) {
      const a = P[i], b = P[i + 1];
      pos.push(a.x, a.y, a.z, b.x, b.y, b.z);
    }

    // Barbs spaced by arc length: an X across the wire (tangent ± vertical).
    const up = new THREE.Vector3(0, 1, 0);
    let acc = 0, nextBarb = barbEvery * 0.5;
    for (let i = 0; i < n - 1; i++) {
      const a = P[i], seg = P[i + 1].clone().sub(a);
      const segLen = seg.length();
      if (segLen < 1e-6) continue;
      const along = seg.clone().multiplyScalar((barbLen * 0.6) / segLen); // tangent · barbLen·0.6
      const vert = up.clone().multiplyScalar(barbLen);
      const d1 = along.clone().add(vert);   // ╱
      const d2 = along.clone().sub(vert);   // ╲
      while (nextBarb <= acc + segLen) {
        const c = a.clone().addScaledVector(seg, (nextBarb - acc) / segLen);
        pos.push(c.x - d1.x, c.y - d1.y, c.z - d1.z, c.x + d1.x, c.y + d1.y, c.z + d1.z);
        pos.push(c.x - d2.x, c.y - d2.y, c.z - d2.z, c.x + d2.x, c.y + d2.y, c.z + d2.z);
        nextBarb += barbEvery;
      }
      acc += segLen;
    }

    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    return g;
  }

  // ─── Barbed wire course rings ─────────────────────────────────────────────
  // §3.6.6: a DOUBLE line of barbed wire is stitched into the bedding joint ON
  // TOP of each finished course — biased toward the interior so it sits under
  // the NEXT ring ("more to the interior of the ring, to hold in place the
  // next ring"). Callers pass `y` = joint height and `r` = the NEXT course's
  // centreline radius; the two strands straddle it at r ± `spread`. `bridges`
  // (optional) connects the ring to the corridor: each entry has the door-gap
  // edge angles { lo, hi } and the jamb point lists { prepend, append }
  // (structure-local {x,z}, ordered mouth→dome / dome→mouth). Where a solid
  // span ends on a door edge, the INNER strand runs out along the jamb to the
  // corridor mouth, so the dome ring and corridor wires are ONE connected line
  // — broken only at real openings (windows, the corridor mouth).
  function buildWireGeometries(y, r, gaps, barbLen, bridges, spread) {
    const spans = solidSpans(gaps);
    const bl = barbLen || 0.045;
    const sp = spread != null ? spread : 0.04;    // half-separation of the pair
    const angNear = (a, b) => {
      const d = (((a - b) % TWO_PI) + TWO_PI) % TWO_PI;
      return d < 2e-3 || Math.abs(d - TWO_PI) < 2e-3;
    };
    const lift = list => list.map(p => new THREE.Vector3(p.x, y, p.z));
    const geoms = [];
    for (const [a0, a1] of spans) {
      const sweep = a1 - a0;
      if (sweep <= 0.01) continue;
      const segs = Math.max(8, Math.round(r * 90 * sweep / TWO_PI));
      for (const rw of [r - sp, r + sp]) {          // the double line
        if (rw <= 0.02) continue;
        let pts = [];
        for (let i = 0; i <= segs; i++) {
          const ang = a0 + (i / segs) * sweep;
          pts.push(new THREE.Vector3(Math.cos(ang) * rw, y, Math.sin(ang) * rw));
        }
        if (bridges && rw < r) {                    // inner strand carries the jamb run
          for (const b of bridges) {
            if (angNear(a0, b.hi)) pts = lift(b.prepend).concat(pts);
            if (angNear(a1, b.lo)) pts = pts.concat(lift(b.append));
          }
        }
        const g = barbedStrand(pts, 0.2, bl);
        if (g) geoms.push(g);
      }
    }
    return geoms;
  }

  // ─── Door corridor / entrance hall (§3.6.7–3.6.8 "deep door mold") ───────
  // The corridor is laid in FLAT HORIZONTAL COURSES, exactly like the dome
  // bags: each course is a straight stadium-bag run on each side of the
  // opening, protruding radially outward at the door azimuth. The head curve
  // (flat / semicircle / arc) is realised by CORBELLING — every course above
  // the springline the two jamb runs step inward, following the head profile,
  // until they close at the crown. Where each course meets the dome it obeys
  // the INTERSECTION RULE: the inner end alternates COVER (tucks into the dome
  // wall) / BUTT (stops at the face), diagonally between the two sides and
  // flipping every course, so the corridor and dome courses interlock.
  // Returns an array of geometries in the structure's LOCAL frame.
  function buildCorridorGeometries(opts) {
    const bw = opts.bagWidthCm / 100;
    const ch = opts.courseHeightCm / 100;
    const section = stadiumSection(bw, ch, 5);
    const geoms = [];
    for (const { y, path } of corridorCoursePaths(opts)) {
      const g = sweepSection(path, y, section, true);
      if (g) geoms.push(g);
    }
    // Rotate corridor to door azimuth in the structure's local frame.
    geoms.forEach(g => g.rotateY(-opts.angle));
    return geoms;
  }

  // Offset a {x,z} polyline perpendicular to its local tangent (for the two
  // strands of the §3.6.6 double wire along straight corridor courses).
  function offsetPathXZ(path, d) {
    const n = path.length, out = [];
    for (let i = 0; i < n; i++) {
      const a = path[Math.max(0, i - 1)], b = path[Math.min(n - 1, i + 1)];
      let tx = b.x - a.x, tz = b.z - a.z;
      const l = Math.hypot(tx, tz) || 1; tx /= l; tz /= l;
      out.push({ x: path[i].x + tz * d, z: path[i].z - tx * d });
    }
    return out;
  }

  // Barbed wire for the corridor: the §3.6.6 DOUBLE strand laid astride the bag
  // centreline in the bedding joint on top of every corridor course, exactly
  // like the dome rings. Built from the SAME course paths as the bags, so the
  // wire and the bags always coincide. Returns LineSegments-ready geometries.
  function buildCorridorWireGeometries(opts) {
    const ch = opts.courseHeightCm / 100;
    const bw = opts.bagWidthCm / 100;
    const bl = ch * 0.35;                 // barb half-size (matches the dome wire)
    const sp = Math.min(0.05, Math.max(0.015, (bw - ch) / 4)); // strand half-separation
    const doorTop = opts.doorTop;
    const geoms = [];
    // Wire mode (ends on the dome centreline). The JAMB courses (y ≤ springline)
    // are drawn by the dome-ring bridges instead, so only the head/lintel courses
    // above the springline are built here.
    for (const { y, path } of corridorCoursePaths(Object.assign({}, opts, { wireEdge: true }))) {
      if (y <= doorTop + 1e-6) continue;
      const wy = y + ch / 2 + 0.004;      // joint height, nudged just proud
      for (const off of [-sp, sp]) {      // the double line
        const pts = offsetPathXZ(path, off).map(p => new THREE.Vector3(p.x, wy, p.z));
        const g = barbedStrand(pts, 0.2, bl);
        if (g) geoms.push(g);
      }
    }
    geoms.forEach(g => g.rotateY(-opts.angle));
    return geoms;
  }

  // The corridor course CENTRELINES — each entry { y, path } is one course laid
  // at constant height y along the {x,z} samples in `path` (a straight jamb run,
  // a corbel capstone, or a flat-head lintel rib). Both the bag meshes and the
  // barbed wire derive from these, so they always agree.
  function corridorCoursePaths(opts) {
    const {
      startR,          // radial start (outer face of dome wall at base)
      profile,         // dome profile → each course begins on the dome surface
      length,          // corridor length (m)
      doorWidth,       // interior width (m)
      doorTop,         // springline height (m) — head curve begins here
      headShape,       // 'flat' | 'semicircle' | 'arc'
      arcHeight,       // m, only used for 'arc'
      bagWidthCm, courseHeightCm,
      maxY,            // optional: build only courses up to this height (Step view)
    } = opts;

    const hs = headShape || 'flat';
    const bw = bagWidthCm / 100;
    const ch = courseHeightCm / 100;
    const cap = maxY != null ? maxY : Infinity;   // the door builds up with the steps
    const Lout = startR + length;                 // outer end of the corridor (x)

    // Where a course centreline at height y and lateral offset zc meets the
    // dome SURFACE (the green junction curve). The dome is a surface of
    // revolution of outer radius Rd(y); a point off-axis by zc sits on it at
    // x = √(Rd² − zc²). As courses rise the dome curves in (Rd shrinks) and as
    // the head corbels (zc shrinks), so the inner ends trace the dome curve.
    function domeStartX(y, zc) {
      let Rd = profile ? outerRadiusAt(profile, bw, y) : null;
      if (Rd == null) Rd = startR;                  // above the dome → base face
      const inside = Rd * Rd - zc * zc;
      return inside > 0 ? Math.sqrt(inside) : Math.max(0.05, Rd - zc);
    }
    // Same, but the INNER dome face (radius Ri(y) = profile inner, sw=0). A
    // COVER course runs all the way to here, spanning the whole wall thickness
    // so the stick-out bag reaches the inside of the dome.
    function domeInnerX(y, zc) {
      let Ri = profile ? outerRadiusAt(profile, 0, y) : null;
      if (Ri == null) Ri = Math.max(0.1, startR - bw);
      const inside = Ri * Ri - zc * zc;
      return inside > 0 ? Math.sqrt(inside) : Math.max(0.05, Ri - zc);
    }
    // The dome CENTRELINE crossing (radius Rc = inner + sw/2). In wire mode the
    // head/lintel courses end here so they meet the dome ring wire (which runs on
    // the centreline) — keeping the corridor and dome wires connected.
    function domeCentreX(y, zc) {
      let Rc = profile ? outerRadiusAt(profile, bw / 2, y) : null;
      if (Rc == null) Rc = Math.max(0.1, startR - bw / 2);
      const inside = Rc * Rc - zc * zc;
      return inside > 0 ? Math.sqrt(inside) : Math.max(0.05, Rc - zc);
    }
    // Wire mode: inner ends sit on the dome centreline (so the wire connects),
    // not on the cover/butt bag faces.
    const wireEdge = !!opts.wireEdge;

    // Interior half-width of the opening at height y (null above a closed crown).
    function halfWidthAt(y) {
      if (y <= doorTop + 1e-9) return doorWidth / 2;
      const dy = y - doorTop;
      if (hs === 'semicircle') {
        const R = doorWidth / 2;
        const sq = R * R - dy * dy;
        return sq > 0 ? Math.sqrt(sq) : null;
      }
      if (hs === 'arc') {
        const arcH = arcHeight || 0.4;
        const hw = doorWidth / 2;
        const R = (hw * hw + arcH * arcH) / (2 * arcH);
        const sq = R * R - (dy - (arcH - R)) * (dy - (arcH - R));
        return sq > 0 ? Math.sqrt(sq) : null;
      }
      return null; // flat: no jamb courses above the springline
    }

    const topY = hs === 'flat'
      ? doorTop
      : doorTop + (hs === 'semicircle' ? doorWidth / 2 : (arcHeight || 0.4));

    const courses = [];

    // Stack the corridor courses bottom → top (only up to the step height).
    let ci = 0;
    for (let y = ch / 2; y <= topY + 1e-6; y += ch, ci++) {
      if (y > cap + 1e-6) break;
      const hw = halfWidthAt(y);
      if (hw === null) continue;

      if (hw + bw / 2 <= bw * 0.55) {
        // Corbel closed: a single capstone course across the centreline,
        // starting on the dome (surface for bags, centreline for the wire).
        const cx = wireEdge ? domeCentreX(y, 0) : domeStartX(y, 0);
        courses.push({ y, path: [{ x: cx, z: 0 }, { x: Lout, z: 0 }] });
        continue;
      }

      const zc = hw + bw / 2;   // jamb bag centreline
      const isJamb = y <= doorTop + 1e-6;   // straight side (below the head)
      for (const side of [-1, 1]) {
        // Diagonal alternation (+z side covers on odd courses, −z on even),
        // complementary to the dome's opening edges. In the straight jamb a
        // COVER course runs the whole wall thickness to the INNER dome face
        // (the stick-out bag), a BUTT course stops on the outer face. The head
        // courses just begin on the dome surface (they form the arch).
        const covers = side > 0 ? (ci % 2 === 1) : (ci % 2 === 0);
        const xInner = wireEdge
          ? domeCentreX(y, zc)                   // wire meets the dome ring centreline
          : isJamb
            ? (covers ? domeInnerX(y, zc) : domeStartX(y, zc))
            : domeStartX(y, zc);
        courses.push({ y, path: [{ x: xInner, z: side * zc }, { x: Lout, z: side * zc }] });
      }
    }

    // Flat head: a lintel of horizontal bag runs spanning the opening, laid
    // across the corridor just above the springline (a flat-roofed door). The
    // inner rib begins on the dome surface at the lintel height.
    if (hs === 'flat' && doorTop + ch / 2 <= cap + 1e-6) {
      const span = doorWidth / 2 + bw / 2;
      const lintelY = doorTop + ch / 2;
      const inX = wireEdge ? domeCentreX(lintelY, span) : domeStartX(lintelY, span);
      const ribs = Math.max(2, Math.round((Lout - inX) / ch));
      for (let r = 0; r < ribs; r++) {
        const xc = inX + (r + 0.5) * ((Lout - inX) / ribs);
        const segs = 4;
        const path = [];
        for (let k = 0; k <= segs; k++) path.push({ x: xc, z: -span + (k / segs) * 2 * span });
        courses.push({ y: lintelY, path });
      }
    }

    return courses;
  }

  // ─── Door collision check: a door must not open into another dome ─────────
  // Returns warning strings for any door whose outward direction leads
  // directly into a neighbour's interior.
  function validateDoorCollisions(s, others) {
    const warnings = [];
    if (!others || !others.length) return warnings;
    const H = s.profile && s.profile.length ? s.profile[s.profile.length - 1].y : 2;
    const openings = computeOpenings(s, H);
    const meRot = (s.rotDeg || 0) * Math.PI / 180;
    const sw = s.bagWidthCm / 100;
    const outerR = s.diameter / 2 + sw;

    for (const o of openings) {
      if (o.kind !== 'door') continue;
      // Local angle → world direction: worldAng = localAng - meRot
      const worldAng = o.angle - meRot;
      const px = (s.x || 0) + Math.cos(worldAng) * (outerR + 0.3);
      const pz = (s.z || 0) + Math.sin(worldAng) * (outerR + 0.3);
      for (const other of others) {
        if (other.type !== 'dome' && other.type !== 'cylinder') continue;
        const dist = Math.hypot(px - (other.x || 0), pz - (other.z || 0));
        if (dist < other.diameter / 2) {
          warnings.push(`Door opens into "${other.name || 'another dome'}" — doors cannot open inside another dome.`);
          break;
        }
      }
    }
    return warnings;
  }

  // Sweep a 2-D `section` ([u,v]) along a 3-D polyline `pts` ({x,y,z}). The
  // section's u-axis is kept RADIAL (horizontal, into/out of the dome wall) and
  // its v-axis perpendicular to both the path tangent and that radial — so a
  // stadium bag follows an arch like a row of voussoirs (the head course bends
  // over the opening while its flat faces stay radial). `capEnds` closes the
  // two ends; `closed` instead joins the last ring back to the first (a loop,
  // e.g. a round window frame). Returns a BufferGeometry or null.
  function sweepSection3D(pts, section, capEnds, closed) {
    const n = pts.length;
    if (n < 2) return null;
    const M = section.length;
    const rings = [];
    for (let i = 0; i < n; i++) {
      const p = pts[i];
      const prev = pts[(i - 1 + n) % n], next = pts[(i + 1) % n];
      const T = closed
        ? new THREE.Vector3(next.x - prev.x, next.y - prev.y, next.z - prev.z)
        : new THREE.Vector3(pts[Math.min(n - 1, i + 1)].x - pts[Math.max(0, i - 1)].x,
                            pts[Math.min(n - 1, i + 1)].y - pts[Math.max(0, i - 1)].y,
                            pts[Math.min(n - 1, i + 1)].z - pts[Math.max(0, i - 1)].z);
      if (T.lengthSq() < 1e-12) T.set(0, 1, 0);
      T.normalize();
      const U = new THREE.Vector3(p.x, 0, p.z);        // horizontal radial (width)
      if (U.lengthSq() < 1e-12) U.set(1, 0, 0);
      U.addScaledVector(T, -U.dot(T));                 // orthogonalise to the tangent
      if (U.lengthSq() < 1e-9) { U.set(1, 0, 0); U.addScaledVector(T, -U.dot(T)); }
      U.normalize();
      const W = new THREE.Vector3().crossVectors(T, U).normalize();
      const ring = [];
      for (let k = 0; k < M; k++) {
        const u = section[k][0], v = section[k][1];
        ring.push([p.x + U.x * u + W.x * v, p.y + U.y * u + W.y * v, p.z + U.z * u + W.z * v]);
      }
      rings.push(ring);
    }
    const pos = [];
    const segN = closed ? n : n - 1;
    for (let i = 0; i < segN; i++) {
      const ni = (i + 1) % n;
      for (let k = 0; k < M; k++) {
        const k2 = (k + 1) % M;
        const a = rings[i][k], b = rings[i][k2], c = rings[ni][k], d = rings[ni][k2];
        pos.push(a[0], a[1], a[2], c[0], c[1], c[2], b[0], b[1], b[2]);
        pos.push(b[0], b[1], b[2], c[0], c[1], c[2], d[0], d[1], d[2]);
      }
    }
    if (capEnds && !closed) {
      [[0, false], [n - 1, true]].forEach(([i, flip]) => {
        const ring = rings[i], c = pts[i];
        for (let k = 0; k < M; k++) {
          const a = ring[k], b = ring[(k + 1) % M];
          if (flip) pos.push(c.x, c.y, c.z, a[0], a[1], a[2], b[0], b[1], b[2]);
          else      pos.push(c.x, c.y, c.z, b[0], b[1], b[2], a[0], a[1], a[2]);
        }
      });
    }
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
    g.computeVertexNormals();
    return g;
  }

  // ─── Door / window HEAD BAG (the "mold" course) ──────────────────────────
  // The top layer of the opening is a CONTINUOUS BAG — the same stadium section
  // as every course — swept along the EXACT head curve (flat lintel / semicircle
  // / arc) on the dome wall. It bends over the opening like a row of voussoirs;
  // the courses above are cut to rest on it (see the mold/buffer logic in
  // openingGaps). Built in the structure's LOCAL frame. Returns geometry or null.
  function buildOpeningHeadBag(o, profile, bagWidthCm, courseHeightCm) {
    if (!profile || !profile.length) return null;
    const bw = bagWidthCm / 100, ch = courseHeightCm / 100;
    const sl = o.springline != null ? o.springline : o.top;
    const crown = o.top;
    const w = o.width;
    const last = profile[profile.length - 1];

    // Wall MID radius at height y (where the course centrelines run).
    const Rmid = y => {
      const inner = outerRadiusAt(profile, 0, y);
      return (inner == null ? last.inner : inner) + bw / 2;
    };

    // Circular ("oculus") window → a closed RING bag framing the round hole.
    if (o.shape === 'circle') {
      const N = 40, ring = [];
      for (let i = 0; i < N; i++) {
        const t = (i / N) * Math.PI * 2;
        const yy = o.cy + o.radius * Math.sin(t);
        const R = Rmid(yy);
        const th = o.angle + (o.radius * Math.cos(t)) / Math.max(0.2, R);
        ring.push({ x: R * Math.cos(th), y: yy, z: R * Math.sin(th) });
      }
      return sweepSection3D(ring, stadiumSection(bw, ch, 5), false, true);
    }
    const headHalf = y => {
      if (y <= sl + 1e-9) return w / 2;
      const dy = y - sl;
      if (o.headShape === 'semicircle') {
        const R = w / 2, sq = R * R - dy * dy; return sq > 0 ? Math.sqrt(sq) : 0;
      }
      if (o.headShape === 'arc') {
        const arcH = o.arcHeight || 0.4, hw = w / 2;
        const R = (hw * hw + arcH * arcH) / (2 * arcH);
        const sq = R * R - (dy - (arcH - R)) * (dy - (arcH - R));
        return sq > 0 ? Math.sqrt(sq) : 0;
      }
      return 0;
    };
    const P = (y, sgn) => {
      const R = Rmid(y);
      const th = o.angle + sgn * (headHalf(y) / Math.max(0.2, R));
      return { x: R * Math.cos(th), y, z: R * Math.sin(th) };
    };

    // The bag runs INTO the course on each side: past the springer it continues
    // horizontally along the wall course (constant height = springline) for ~1½
    // bags, so the arch flows smoothly out of — and back into — the corresponding
    // top layer instead of ending in a floating cap.
    const R0 = Rmid(sl);
    const aR = (w / 2) / R0;                 // door half-angle at the springline
    const extAng = (bw * 1.5) / R0;          // run-in length along the course
    const onCourse = th => ({ x: R0 * Math.cos(th), y: sl, z: R0 * Math.sin(th) });

    const pts = [];
    if (o.headShape === 'flat' || crown <= sl + 1e-6) {
      // Flat lintel: a straight bag across the top, extended into the courses.
      const N = 12;
      const a0 = o.angle - aR - extAng, a1 = o.angle + aR + extAng;
      for (let i = 0; i <= N; i++) pts.push(onCourse(a0 + (i / N) * (a1 - a0)));
    } else {
      const N = 18;
      pts.push(onCourse(o.angle + aR + extAng));         // +side run-in
      pts.push(onCourse(o.angle + aR + extAng * 0.5));
      for (let i = 0; i <= N; i++) pts.push(P(sl + (crown - sl) * (i / N), +1)); // up +edge to crown
      for (let i = N - 1; i >= 0; i--) pts.push(P(sl + (crown - sl) * (i / N), -1)); // down −edge
      pts.push(onCourse(o.angle - aR - extAng * 0.5));   // −side run-out
      pts.push(onCourse(o.angle - aR - extAng));
    }
    if (pts.length < 2) return null;
    return sweepSection3D(pts, stadiumSection(bw, ch, 5), true);
  }

  // ─── Plaster shells ──────────────────────────────────────────────────────
  function buildPlasterGeometry(profile, bagWidthCm, plasterThicknessCm) {
    if (!profile || profile.length < 2) return null;
    const pt = plasterThicknessCm / 100;
    const bw = bagWidthCm / 100;
    const outerPts = profile.map(c => new THREE.Vector2(c.r + bw / 2 + pt, c.y));
    return new THREE.LatheGeometry(outerPts, 64);
  }

  function buildInnerPlasterGeometry(profile, bagWidthCm, plasterThicknessCm) {
    if (!profile || profile.length < 2) return null;
    const pt = plasterThicknessCm / 100;
    const bw = bagWidthCm / 100;
    const innerPts = profile.map(c => new THREE.Vector2(Math.max(0.01, c.r - bw / 2 - pt), c.y));
    return new THREE.LatheGeometry(innerPts, 64);
  }

  // ─── Shared ground terrain ───────────────────────────────────────────────
  function buildTerrainGeometry(extent) {
    const size = Math.max(20, extent);
    const geom = new THREE.PlaneGeometry(size, size, 1, 1);
    geom.rotateX(-Math.PI / 2);
    // Very subtle ~8 mm displacement for visual ground texture — kept small so the
    // plane reads as flat rather than sloped when viewed at a low camera angle.
    geom.computeVertexNormals();
    return geom;
  }

  // ─── Foundation ring ─────────────────────────────────────────────────────
  function buildFoundationGeometry(innerRadius, bagWidthCm) {
    const bw = bagWidthCm / 100;
    const outerR = innerRadius + bw + 0.05;
    const innerR = Math.max(0.05, innerRadius - 0.1);
    const shape = new THREE.Shape();
    shape.absarc(0, 0, outerR, 0, TWO_PI, false);
    const hole = new THREE.Path();
    hole.absarc(0, 0, innerR, 0, TWO_PI, true);
    shape.holes.push(hole);
    const geom = new THREE.ExtrudeGeometry(shape, { depth: 0.3, bevelEnabled: false });
    geom.rotateX(-Math.PI / 2);
    geom.translate(0, -0.3, 0);
    return geom;
  }

  return {
    domeProfile,
    domeHeight,
    coherency,
    cylinderProfile,
    vaultProfile,
    recommendedSack,
    OPENING_RULES,
    computeOpenings,
    validateOpenings,
    maxDoorWidth,
    validateDoorCollisions,
    openingGaps,
    intersectionGaps,
    idealApse,
    buttressCourses,
    solidFraction,
    sliceSpans,
    buildShellGeometry,
    buildCourseGeometries,
    buildWireGeometries,
    barbedStrand,
    buildCorridorGeometries,
    buildCorridorWireGeometries,
    buildOpeningHeadBag,
    buildPlasterGeometry,
    buildInnerPlasterGeometry,
    buildTerrainGeometry,
    buildFoundationGeometry,
  };

})();
